### ISSUE TITLE
Crash when exiting application

### ISSUE THREAD

**Issue by CoderJoeW** [flaminggenius/CSVAnalyzerPro#1]
Sometimes app crashes when exiting the program 

Code
```c# 
Environment.Exit (1);
```

Cause: "Error Creating Window Handle"

**Comment by wojciechowskiapp** [comment]
Try to use 
`Application.Exit();`
Instead of 
`Environment.Exit (1);`

**Comment by CoderJoeW** [comment]
Tested with the above still crashes I think it's related to having multiple pages opened with large files doesn't seem to crash when having a file open with less then 1000 lines

**Comment by KoromaruKoruko** [comment]
i sugest then making a global exit function that unloads all the files and then exits
