### ISSUE TITLE
Switch from grid to spreadsheet

### ISSUE THREAD

**Issue by CoderJoeW** [flaminggenius/CSVAnalyzerPro#10]
I'm considering switching from grid's to spreadsheets and allowing more file types and importing/exporting excel format 

I haven't put much thought into the layout design as many may have noticed by now my sole focus has been maintaining a multi-window view

I would like to add a ribbon like excel has up top 

The way things are currently setup one ribbon would be programmed to work on each different page based on `tabControl1.selectedIndex`

Should I continue with this approach or would it be better to dynamically create a ribbon with the spreadsheet in the `NewWindow` function

Reference Branch: [https://github.com/flaminggenius/CSVAnalyzerPro/tree/Experimental-0.0.4(Spreadsheet-edition)](https://github.com/flaminggenius/CSVAnalyzerPro/tree/Experimental-0.0.4(Spreadsheet-edition))

**Comment by dl471** [comment]
So you'd keep tabControl1 in either case but drop GridDataBoundGrid in favour of something else?

I'd say go with your current approach for now. What would be better in the long run seems like something that will be answered as you get more into the details of what you'd like the ribbon to do and how.

**Comment by CoderJoeW** [comment]
I started using the grids as a mean to design the basic layout of the program but it's extendability is poor at best. I was looking at some professional grade softwares like excel and they are using spreadsheet views and not gridViews so in the future I may switch to that

As far as the ribbon goes I really wanna replace that ugly context menu it just doesn't fit with what's considered "modern" design it's really an eye sore and it's something I wanna fix in 0.0.4. My main struggle is weather the ribbon should be dynamically created or should it be static like the current context menu Strip is.

I went over pros and cons of both the major con to dynamically creating the ribbon(which is the approach I favor more) is how will the basic functions be handled? (Like creatING a new window)

I thought maybe adding controls to the welcome page since it's a static page but then users would have to constantly go back to the welcome page to create a new window and then there's a chance they could accidentally close the welcome page in which case they would have to relaunch the application to create a new window

I've given it a lot of thought bUT can't seem to find a good solution

**Comment by dl471** [comment]
It should be fairly straight forward to make the Welcome page unclosable, but I agree that making the user navigate back to the main window each time would be unwieldy.

What are the main benefits of having dynamic ribbons? Could the creation of new windows remain centralized in one instance with the ribbons being given a way to call that? If the spreadsheets and ribbons are treated as being tied to specific tabs and the class that creates new windows is its own thing I think that could work.

**Comment by CoderJoeW** [comment]
The main benefit to having dynamic ribbons is the ability to bind them directly to a spreadsheet vs if we have a static ribbon we would have to program  every function on the ribbon to work based on the selected tab which also means that every time the user switches tabs the ribbon has to rebind itself to another spreadsheet

I imagine that would be very costly performance wise

**Comment by CoderJoeW** [comment]
Ive started working on a prototype in a seperate branch from the master branch which will remain using `GridDataBoundGrid` unless a stable version can be made using spreadsheets 

I started working torwards the dynamic approach but its quite buggy atm
