### ISSUE TITLE
Crash when clicking new on file menu in Spreadsheet branch

### ISSUE THREAD

**Issue by dl471** [flaminggenius/CSVAnalyzerPro#15]
I thought it'd make sense to continue discussion of this in a new issue.

I just want to clarify the intended behaviour. It should just reset the current file, right?

**Comment by CoderJoeW** [comment]
It should I went ahead and hid the file tab in the ribbon until I can figure out what's causing it to crash

**Comment by dl471** [comment]
It seems like the crash is related to an element called BackStageView, specifically the fact that that sRibbon does not have one. I was able to prevent the crash by creating a dummy BackStageView for sRibbon but I can't get said BackStageView to properly display. I'm not all that familiar with the library being used so maybe you'll have more luck.

**Comment by CoderJoeW** [comment]
With the new command system this is no longer an issue
