### ISSUE TITLE
Touching up readme and wiki

### ISSUE THREAD

**Issue by CoderJoeW** [flaminggenius/CSVAnalyzerPro#22]
The readme could use more detailed information dn possibly a better look

**Comment by 0x48piraj** [comment]
I'm on it ! Hold tight :wink:

**Comment by 0x48piraj** [comment]
Done ! Here's the Pull Request ! [#24](https://github.com/flaminggenius/CSVAnalyzerPro/pull/24)
> I started today contributing ! Hope you like it :smile:

**Comment by CoderJoeW** [comment]
Much appreciated
