### ISSUE TITLE
Search functionality(ctrl+f)

### ISSUE THREAD

**Issue by CoderJoeW** [flaminggenius/CSVAnalyzerPro#23]
Why have I not done this yet??

Yeah one of the key features needed is a nice search panel when hitting `ctrl+f` this will be registered in the keyboardshortcuts (thanks #17 )

I guess for now a simple search functionality would work that just drills down to the data like in the main branch the search function I would also like to use a similiar syntax and allow sql like search but that can be added later on I suppose

**Comment by CSJedi** [comment]
Hi, I want yo do this
