### ISSUE TITLE
#28 Resolve conflicts

### ISSUE THREAD

**Issue by CoderJoeW** [flaminggenius/CSVAnalyzerPro#29]
I dont use git and am unfamiliar with resolving these conflicts or how they arose so anyone who can shine light on that i would be very grateful too

**Comment by ealvesss** [comment]
which conflict?

**Comment by hunbernd** [comment]
I give it a try, please check this version: https://github.com/hunbernd/CSVAnalyzerPro
If it is working for you, then I can give you instructions, how to fix your repo.

**Comment by CoderJoeW** [comment]
Here's an image

[https://ibb.co/bEHgAm](https://ibb.co/bEHgAm)

**Comment by hunbernd** [comment]
You cannot merge these files on github easily, you should merge them locally on your computer and push the merge commit. 
You will need a tool, I suggest Tortoisegit, or Meld.

The deleted and then uploaded files just make git confused, I suggest to remove this commits first and then attempt to merge again.

**Comment by CoderJoeW** [comment]
Yeah never ran across the issue before I will revert the latest commits and then try one of those tools
