### ISSUE TITLE
thisVersion and version returned by update.php inconsistent?

### ISSUE THREAD

**Issue by dl471** [flaminggenius/CSVAnalyzerPro#3]
CheckUpdate_Load in CheckUpdate.cs defines thisVersion as 0.0.3. However, the source that I have seen for the 0.0.3 build appears to direct the program to update.php which returns 0.0.2 as the latest version.

Could you establish which version is correct and change either thisVersion or update.php to reflect your decision?

**Comment by CoderJoeW** [comment]
I forgot to switch over the versions that was my bad its fixed now
